version: '2'
services:
    appusr-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/appusr/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=appusr
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
